### ISSUE TITLE
[FEATURE] Add Proper Documentation

### ISSUE THREAD

**Issue by ptsouchlos** [ptsouchlos/eventbus#27]
We need to add proper documentation to the code. This can also include integrating Doxygen and auto publishing documentation to Github pages.

Sample workflow:

```yaml
name: Documentation

on:
  push:
    tags:
      - "*"

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          brew install doxygen
          pip3 install jinja2 Pygments
      - name: Build
        run: |
          cmake -Sdocumentation -Bbuild
          cmake --build build --target GenerateDocs
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html
```
